export { default as Page } from './Page'
export { default as Header } from './Header'
export { default as Search } from './Search'
export { default as Movies } from './Movies'
export { default as MovieCard } from './MovieCard'
